### PR TITLE
Why skip income

### PR DESCRIPTION
**Pull request by phiden**
Explain why the income section gets skipped if the household receives SNAP, TANF or FDPIR

### CODE REVIEW

**Comment by phiden** [comment]
ready for review! Closes #56.

**Comment by dannychapman** [comment]
It seems to jump me right past the income section to review?

**Comment by phiden** [comment]
That’s correct, assuming you’ve answered ‘yes’ to the additional assistance question.

**Comment by dannychapman** [comment]
@phiden can you point me to where this text added to app.js appears?

**Pull request merged**
