### PR TITLE
Yes/no radio buttons for has other help & has SSN

### PR DESCRIPTION
**Pull request by paulsmith**
If the user has not yet responded to these, neither yes/no radio button should be checked.

### CODE REVIEW

**Comment by paulsmith** [comment]
Addresses #159.

**Comment by paulsmith** [comment]
Addresses #155 and #156.

**Comment by paulsmith** [comment]
Addresses #137

**Comment by greggersh** [comment]
:+1:

**Comment by paulsmith** [comment]
Closes #137.

**Pull request closed without merging**
